services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    # volumes:
    #   - .:/cvlmback
    container_name: cvlm
    ports:
      - "8000:8000"
    environment:
      GEMINI_KEY: ${GEMINI_KEY}
    env_file:
      - .env
    healthcheck:
      test: ['CMD', 'curl', 'http://0.0.0.0:8000/healthcheck']
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 3s
# volumes:
