services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    # volumes:
    #   - .:/cvlmback
    container_name: cvlm
    ports:
      - "8000:8000"
    environment:
      GEMINI_KEY: ${GEMINI_KEY}
    env_file:
      - .env
# volumes:
