name: chessllm CI

on:
  push:
  pull_request:

jobs:
  setup_steps: &setup
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Create .env file
      run: echo GEMINI_KEY=${{ secrets.GEMINI_KEY }} >> .env

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - *setup
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
        
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.3"

      - name: Install dependencies
        run: uv sync --locked

      - name: Start server
        run: uv run gunicorn -k uvicorn.workers.UvicornWorker -w 4 -b 0.0.0.0:8000 app.main:app

      - name: Run tests
        run: uv run pytest app/tests
  
  # build-docker:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v4
      
  #     - name: Set up Docker build
  #       uses: docker/setup-buildx-action@v3

  #     - name: Build Docker Compose services
  #       run: docker compose up --build 

