name: chessllm CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
        
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.3"

      - name: Install dependencies
        run: uv sync --locked

      - name: Start server
        run: uv run fastapi dev app/main.py

      - name: Run tests
        run: uv run pytest app/tests
  
  # build-docker:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v4
      
  #     - name: Set up Docker build
  #       uses: docker/setup-buildx-action@v3

  #     - name: Build Docker Compose services
  #       run: docker compose up --build 

